name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Start
      run: wget https://raw.githubusercontent.com/jtgrassie/pyrx/master/tests/test.py
    - run: python --version
    - run: pip install pyrx
    # - run: python test.py
    - run: ls
    
